### ISSUE TITLE
Doesn't require curl, fails when it isn't installed

### ISSUE THREAD

**Issue by naftulikay** [voxpupuli/puppet-rabbitmq#145] opened 2013-11-22 22:09 UTC
Unfortunately, on Ubuntu 12.04, `curl` isn't installed by default. When I try installing this module, it fails because it can't download something with curl. Maybe just adding `curl` as a required package would fix the problem?

**Comment by wyardley** [comment] 2017-08-17 23:08
Responding to a [very old] issue:

I think it will work with either `curl`  or `wget`, though we  should move to the `archive` module instead of `staging` probably... 
I guess this is a grey area, it's not exactly a soft dep, since it's required to work in order to install rabbitmqadmin, but any deps should probably be dealt with via `ensure_packages()` in the module we're using to handle this. If I get a chance, I'll try to rework it to use archive module. If that doesn't force curl or wget to be present, we might need to also add a note in the README at least?

**Comment by wyardley** [comment] 2017-08-17 23:08
ps - I think either `curl` or `wget` is probably reliably on the typical types of supported systems now, so maybe this can just be closed?

**Comment by wyardley** [comment] 2017-09-11 19:01
dupe of #142
We are using archive module now. I will verify its behavior.

**Closed by wyardley** 2017-09-11 19:01 UTC
