### ISSUE TITLE
not working with rabbitmq-server 3.7 - Cannot parse invalid user line

### ISSUE THREAD

**Issue by heap98** [voxpupuli/puppet-rabbitmq#671] opened 2017-12-06 16:06 UTC
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.3.3-1xenial
- Ruby: ruby2.4 (included in puppet package)
- Distribution: Ubuntu 16.04.3 LTS
- Module version: v8.0.0
- Rabbitmq-server : 3.7.0-1

## How to reproduce (e.g Puppet code you use)
just run
puppet agent -t

```puppet
      rabbitmq_user { 'new_user':
                admin    => true,
                password => 'pass',
                provider => 'rabbitmqctl'
        }
```

## What are you seeing
```
Error: Failed to apply catalog: Cannot parse invalid user line: warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
```
## What behaviour did you expect instead
something went wrong with name encoding when the module is trying to fetch the result of the command: 
/usr/sbin/rabbitmqctl -q list_users

the function itself is located in this file line 22:
./lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb

## Output log
```
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_users'
Debug: Command succeeded
Debug: Storing state
Debug: Stored state in 0.16 seconds
Error: Failed to apply catalog: Cannot parse invalid user line: warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
Debug: Dynamically-bound server lookup failed, falling back to report_server setting
```

## Any additional information you'd like to impart

**Comment by wyardley** [comment] 2017-12-06 18:13
@heap98:
What's the output of `rabbitmqctl -q list_users`? Does it have that same warning:
`warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)`?

**Comment by heap98** [comment] 2017-12-07 09:11
puppet runs as user root. output of the command is following and looks fine.

> root@rabbit01:~# rabbitmqctl -q list_users
guest	[administrator]
> 



`update-locale  LC_ALL=en_US.UTF-8`

doesn't fix the issue.


output von locale:

>[root@rabbit01 ~]$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
>

**Comment by wikimatze** [comment] 2017-12-07 10:19
I have a similar error. The solution for this is to use:

```ruby
def self.instances
    user_list = run_with_retries do
      rabbitmqctl('-q', 'list_users')
    end

    user_list = `/usr/sbin/rabbitmqctl -q list_users`
    ....
```

instead of:

```ruby
 def self.instances
    user_list = run_with_retries do
      rabbitmqctl('-q', 'list_users')
    end

    user_list.split(%r{\n}).map do |line|
      ....
    end
```

So the problem arise with the mapped usage of `modules/rabbitmq/lib/puppet/provider/rabbitmqctl.rb` command within the project. Even if I set `#encoding: UTF-8` at the beginning of the file, it does not solve the problem.

**Comment by mUbsta** [comment] 2017-12-07 23:11
```
class {'rabbitmq':
  environment_variables => {
    'LC_ALL' => 'en_GB.UTF-8',
  }
}
``` 
Gets around this issue

**Comment by wikimatze** [comment] 2017-12-08 11:47
@mUbsta thanks for the advice, I'll try this.

**Comment by desertkun** [comment] 2017-12-08 14:42
@mUbsta thank you very much, you have saved my life here.

**Comment by wyardley** [comment] 2017-12-08 18:57
I wonder if there's a good fix to this that's clean but avoids explicitly hard coding locales / env variables. Maybe we could capture stderr from the command and only print it in the output it if the command fails?

**Comment by ThaDanus** [comment] 2017-12-19 13:53
Thank you very much @mUbsta, this had us stumped for a couple of days!

**Comment by alexizmailov** [comment] 2017-12-21 04:22
After adding `  environment_variables => {
    'LC_ALL' => 'en_GB.UTF-8',
  }` 
this ocurres:

```
root@dev-mq-02:~  #
root@dev-mq-02:~  # pat
Info: Using configured environment '186312_mq'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for dev-mq-02.svc.int.ix.org.au
Info: Applying configuration version '1513829253'
Notice: /Stage[main]/Rabbitmq::Config/File[rabbitmq-env.config]/content:
--- /etc/rabbitmq/rabbitmq-env.conf	2017-12-21 14:27:26.551001889 +1100
+++ /tmp/puppet-file20171221-7604-1tcbc9v	2017-12-21 15:08:13.587487767 +1100
@@ -1,3 +1,4 @@
+LC_ALL=en_GB.UTF-8
 NODENAME=rabbit
 NODE_IP_ADDRESS=0.0.0.0
 NODE_PORT=5672

Notice: /Stage[main]/Rabbitmq::Config/File[rabbitmq-env.config]/content:

Notice: /Stage[main]/Rabbitmq::Config/File[rabbitmq-env.config]/content: content changed '{md5}41196d5c8c9a6193a4f956922ad6d8b4' to '{md5}be8c2728663459a409e45fab8311fef4'
Info: /Stage[main]/Rabbitmq::Config/File[rabbitmq-env.config]: Scheduling refresh of Class[Rabbitmq::Service]
Info: Class[Rabbitmq::Config]: Scheduling refresh of Class[Rabbitmq::Service]
Info: Class[Rabbitmq::Service]: Scheduling refresh of Service[rabbitmq-server]
Notice: /Stage[main]/Rabbitmq::Service/Service[rabbitmq-server]: Triggered 'refresh' from 1 event
Error: /Stage[main]/Profiles::Services::Rabbitmq::Docker_app_accounts/Profiles::Services::Rabbitmq::User[hsnet-admin_docker_dev]/Rabbitmq_policy[ha-all@hsnet-admin_docker_dev]: Could not evaluate: cannot parse line from list_policies:hsnet-admin_docker_dev	ha-all	.*	all	{"ha-mode":"all","ha-sync-mode":"automatic"}	0
Error: /Stage[main]/Profiles::Services::Rabbitmq::Docker_app_accounts/Profiles::Services::Rabbitmq::User[hsnet-admin-test_docker_dev]/Rabbitmq_policy[ha-all@hsnet-admin-test_docker_dev]: Could not evaluate: cannot parse line from list_policies:hsnet-admin-test_docker_dev	ha-all	.*	all	{"ha-mode":"all","ha-sync-mode":"automatic"}	0
Error: /Stage[main]/Profiles::Services::Rabbitmq::Docker_app_accounts/Profiles::Services::Rabbitmq::User[s2x_docker_dev]/Rabbitmq_policy[ha-all@s2x_docker_dev]: Could not evaluate: cannot parse line from list_policies:s2x_docker_dev	ha-all	.*	all	{"ha-mode":"all","ha-sync-mode":"automatic"}	0
Error: /Stage[main]/Profiles::Services::Rabbitmq::Docker_app_accounts/Profiles::Services::Rabbitmq::User[s2x-test_docker_dev]/Rabbitmq_policy[ha-all@s2x-test_docker_dev]: Could not evaluate: cannot parse line from list_policies:s2x-test_docker_dev	ha-all	.*	all	{"ha-mode":"all","ha-sync-mode":"automatic"}	0
Error: /Stage[main]/Profiles::Services::Rabbitmq::Docker_app_accounts/Profiles::Services::Rabbitmq::User[iss3_docker_dev]/Rabbitmq_policy[ha-all@iss3_docker_dev]: Could not evaluate: cannot parse line from list_policies:iss3_docker_dev	ha-all	.*	all	{"ha-mode":"all","ha-sync-mode":"automatic"}	0
Error: /Stage[main]/Profiles::Services::Rabbitmq::Docker_app_accounts/Profiles::Services::Rabbitmq::User[iss3-test_docker_dev]/Rabbitmq_policy[ha-all@iss3-test_docker_dev]: Could not evaluate: cannot parse line from list_policies:iss3-test_docker_dev	ha-all	.*	all	{"ha-mode":"all","ha-sync-mode":"automatic"}	0
Error: /Stage[main]/Profiles::Services::Rabbitmq::Docker_app_accounts/Profiles::Services::Rabbitmq::User[profiles_docker_dev]/Rabbitmq_policy[ha-all@profiles_docker_dev]: Could not evaluate: cannot parse line from list_policies:profiles_docker_dev	ha-all	.*	all	{"ha-mode":"all","ha-sync-mode":"automatic"}	0
Error: /Stage[main]/Profiles::Services::Rabbitmq::Docker_app_accounts/Profiles::Services::Rabbitmq::User[profiles-test_docker_dev]/Rabbitmq_policy[ha-all@profiles-test_docker_dev]: Could not evaluate: cannot parse line from list_policies:profiles-test_docker_dev	ha-all	.*	all	{"ha-mode":"all","ha-sync-mode":"automatic"}	0
Error: /Stage[main]/Profiles::Services::Rabbitmq::Docker_app_accounts/Profiles::Services::Rabbitmq::User[oneplace_docker_dev]/Rabbitmq_policy[ha-all@oneplace_docker_dev]: Could not evaluate: cannot parse line from list_policies:oneplace_docker_dev	ha-all	.*	all	{"ha-mode":"all","ha-sync-mode":"automatic"}	0
Error: /Stage[main]/Profiles::Services::Rabbitmq::Docker_app_accounts/Profiles::Services::Rabbitmq::User[oneplace-test_docker_dev]/Rabbitmq_policy[ha-all@oneplace-test_docker_dev]: Could not evaluate: cannot parse line from list_policies:oneplace-test_docker_dev	ha-all	.*	all	{"ha-mode":"all","ha-sync-mode":"automatic"}	0
Error: /Stage[main]/Profiles::Services::Rabbitmq::Docker_app_accounts/Profiles::Services::Rabbitmq::User[nagios]/Rabbitmq_policy[ha-all@/]: Could not evaluate: cannot parse line from list_policies:/	ha-all	.*	all	{"ha-mode":"all","ha-sync-mode":"automatic"}	0
Info: Stage[main]: Unscheduling all events on Stage[main]
```
So, this solution removes one problem and introduces another one.

**Comment by alexizmailov** [comment] 2017-12-27 04:20
Created a PR to resolve this ^^^
https://github.com/voxpupuli/puppet-rabbitmq/pull/674

**Comment by waza-ari** [comment] 2018-02-08 16:16
Hm, it looks I'm also hitting this bug with latest 8.1.0 code. Distribution is CentOS 7, but also RHEL 6.8 seems to be affected.

**Comment by oneiros-de** [comment] 2018-03-19 15:38
We are seeing the same issue with Debian 8.10 and RabbitMQ 3.7.2 on Erlang 20.1

**Comment by wyardley** [comment] 2018-03-19 18:40
Can someone post the actual `list_users` output from one of the affected systems?

**Comment by oneiros-de** [comment] 2018-03-20 15:30
`guest	[administrator]`

**Comment by wyardley** [comment] 2018-04-04 05:57
Can you see if #690 resolves this?

**Comment by oneiros-de** [comment] 2018-04-05 09:50
@wyardley Doesn't seem so
```
root@test-icms-rabbitmq1:/home/martinsc # puppet agent --test --noop
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Applying configuration version '1522921614'
Error: Failed to apply catalog: Cannot parse invalid user line: warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)
root@test-icms-rabbitmq1:/home/martinsc # locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```

**Comment by michaelklishin** [comment] 2018-04-06 00:10
This is [an Elixir requirement](https://github.com/elixir-lang/elixir/issues/3548) and their team seems to feel strongly about this.

Configuration software that uses CLI tools can override locale environment variables for the calls that expect an output that is parsed:

```
LANG="en_US.UTF-8" LC_ALL="en_US.UTF-8" rabbitmqctl …
```

Team RabbitMQ will consider forcing this in our shell scripts (https://github.com/rabbitmq/rabbitmq-server/issues/1573) but IIRC this has been considered before and rejected.

**Comment by wyardley** [comment] 2018-04-09 22:26
Merged a fix that forces `en_US.UTF-8` vs. `C`, which fixes in my test environment.
Happy to help if someone wants to play with a fix that actually ignores the output, but I think this would require significantly more effort for maybe not much gain.

**Closed** 2018-04-09 22:33 UTC

**Comment by jurim76** [comment] 2018-11-18 12:52
Same issue again

In rabbitmq-3.7.9 added a new string "user tags", that breaks output parsing

> rabbitmqctl list_users
Listing users ...
user    tags
comps   [management]
tr3     [management]
admin   [administrator]
sugarcrm        [management]
backup  [administrator, management]
zabbix  [monitoring]
tasks   [management]

Puppet exit with error

"Error: Failed to apply catalog: Cannot parse invalid user line: user    tags"

**Comment by benpollard** [comment] 2018-11-18 14:00
See https://github.com/rabbitmq/rabbitmq-cli/issues/273 for details on how to solve this issue.

**Comment by dduuch** [comment] 2018-12-03 12:32
> See [rabbitmq/rabbitmq-cli#273](https://github.com/rabbitmq/rabbitmq-cli/issues/273) for details on how to solve this issue.

So the issue is not resolved for new rabbitmq.

**Comment by NimishKmr** [comment] 2021-05-28 19:28
Is this fixed? I too get same error when using in puppet..

**Error -**
Error: /Stage[main]/Mymodule::Rabbitmq/Rabbitmq_user_permissions[newdev@newdev]: Could not evaluate: cannot parse line from list_user_permissions:warning: the VM is running with native name encoding of latin1 which may cause Elixir to malfunction as it expects utf8. Please ensure your locale is set to UTF-8 (which can be verified by running "locale" in your shell)

**Puppet config -** 
#Configure RabbitMQ
        rabbitmq_user { "$rabbitmq_user":
          admin    => false,
          password => "${rabbitmq_pass}",
          provider => 'rabbitmqctl',
          tags     => ['policymaker'],
        }->
        rabbitmq_vhost { "$rabbitmq_vhost":
          provider => 'rabbitmqctl',
