### ISSUE TITLE
unexpected token error at arguments

### ISSUE THREAD

**Issue by itnazeer** [voxpupuli/puppet-rabbitmq#768] opened 2019-01-23 11:29 UTC
Hi,
I have written queue and it updated fine in puppet node, again if I run to add another queue getting below error. Please help on this
```
Debug: Command succeeded
Debug: Executing: '/bin/systemctl is-active rabbitmq-server'
Debug: Executing: '/bin/systemctl is-enabled rabbitmq-server'
Debug: Executing: '/bin/rpm -q rabbitmqadmin --nosignature --nodigest --qf '%{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n''
Debug: Executing: '/bin/rpm -q rabbitmqadmin --nosignature --nodigest --qf '%{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n' --whatprovides'
Debug: /Stage[main]/Rabbitmq::Install::Rabbitmqadmin/Package[rabbitmqadmin]: Nothing to manage: no ensure and the resource doesn't exist
Debug: Prefetching rabbitmqadmin resources for rabbitmq_queue
Debug: Executing: '/sbin/rabbitmqctl list_vhosts -q'
Debug: Executing: '/sbin/rabbitmqctl list_queues -q -p name name durable auto_delete arguments'
Debug: Executing: '/sbin/rabbitmqctl list_queues -q -p / name durable auto_delete arguments'
Debug: Storing state
Debug: Stored state in 0.16 seconds
Error: Failed to apply catalog: 751: unexpected token at 'arguments'
```

**Comment by dduuch** [comment] 2019-01-24 12:58
Duplicated with https://github.com/voxpupuli/puppet-rabbitmq/issues/763

**Comment by wyardley** [comment] 2019-01-24 15:05
Can you clarify your module and rmq versions? Is this with current master or an older version?

**Comment by wyardley** [comment] 2019-01-24 15:09
If this is a dupe of #763 and / or this error still comes up with current master, let’s reopen that and / or delay the release.

**Comment by itnazeer** [comment] 2019-01-25 02:45
Hi I am using puppet module version 8.4.1.


Thanks
Nazeer


________________________________

**Comment by wyardley** [comment] 2019-01-25 03:45
What RMQ version?

Can you confirm if 8.5.0 resolves the issue for you?

**Comment by itnazeer** [comment] 2019-01-25 03:56
RMQ version is 3.7.10

I will try with 8.5.0

Thanks
Nazeer

________________________________

**Comment by wyardley** [comment] 2019-01-25 04:06
> RMQ version is 3.7.10

FWIW, the version you’re using has multiple bugs with >= 3.7.9 (and README doesn’t claim support for 3.7.x at all, not do acceptance tests test it). We hope that 8.5.0 will fix many of these tho there still may be additional issues.

**Closed** 2019-01-28 19:06 UTC
Labels: question
