### ISSUE TITLE
rabbitmq_user_permissions timing out

### ISSUE THREAD

**Issue by cdenneen** [voxpupuli/puppet-rabbitmq#689] opened 2018-03-20 16:20 UTC
- Puppet: 4.10.1
- Ruby: 2.1.9 (puppet embedded)
- Distribution: Centos7
- Module version: 7.1.0, 8.1.0
- Rabbitmq: rabbitmq-server-3.3.5-34.el7.noarch

## How to reproduce (e.g Puppet code you use)
```
class { '::rabbitmq':
  environment_variables => {
    'node_ip_address' => '127.0.0.1',
  },
}

# Fixing a broken dependency
Package['rabbitmq-server'] -> Service['rabbitmq-server']

  rabbitmq_user { 'sensu':
    password => 'readonly',
    require  => Service['rabbitmq-server'],
  }
  -> rabbitmq_vhost { '/sensu':
    ensure  => present,
  }
  -> rabbitmq_user_permissions { 'sensu@/sensu':
    configure_permission => '.*',
    read_permission      => '.*',
    write_permission     => '.*',
  }
```
## What are you seeing
Have 2 prompts open to server running apply:

1. puppet apply
```
Debug: Prefetching rabbitmqctl resources for rabbitmq_user
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_users'
Debug: Command succeeded
Notice: /Stage[main]/Profile::Sensu_server_enterprise/Rabbitmq_user[sensu]/ensure: current_value absent, should be present (noop)
Debug: /Stage[main]/Profile::Sensu_server_enterprise/Rabbitmq_user[sensu]: The container Class[Profile::Sensu_server_enterprise] will propagate my refresh event
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_vhosts'
Debug: Command succeeded
Notice: /Stage[main]/Profile::Sensu_server_enterprise/Rabbitmq_vhost[/sensu]/ensure: current_value absent, should be present (noop)
Debug: /Stage[main]/Profile::Sensu_server_enterprise/Rabbitmq_vhost[/sensu]: The container Class[Profile::Sensu_server_enterprise] will propagate my refresh event
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Debug: Executing: '/usr/sbin/rabbitmqctl -q list_user_permissions sensu'
Debug: Command failed, retrying
Error: /Stage[main]/Profile::Sensu_server_enterprise/Rabbitmq_user_permissions[sensu@/sensu]: Could not evaluate: Command is still failing after 180 seconds expired!
```

at the same time as the "retrying" getting the following on second terminal
```
[root@sensu-server-enterprise /]# /usr/sbin/rabbitmqctl -q list_user_permissions sensu
Error: no_such_user: sensu
[root@sensu-server-enterprise /]# /usr/sbin/rabbitmqctl -q list_user_permissions sensu
Error: no_such_user: sensu
[root@sensu-server-enterprise /]# /usr/sbin/rabbitmqctl -q list_user_permissions sensu
Error: no_such_user: sensu
[root@sensu-server-enterprise /]# /usr/sbin/rabbitmqctl -q list_user_permissions sensu
Error: no_such_user: sensu
[root@sensu-server-enterprise /]#
```

## What behaviour did you expect instead
Expect puppet run to get no_such_user return and not timeout

**Comment by cdenneen** [comment] 2018-03-20 20:26
Docs still maintain to use EPEL for EL distros.
EPEL latest `rabbitmq-server` is `3.3.5-34`. erlang is pretty old too using garethr-erlang.
So the options are to switch to using packagecloud for both `rabbitmq/rabbitmq-server` and `rabbitmq/erlang`.

so the puppet code above has be migrated to:

```
  class { '::rabbitmq':
    repos_ensure          => true,
    environment_variables => {
      'LC_ALL'          => 'en_US.UTF-8',
      'node_ip_address' => '127.0.0.1',
    },
  }
```

**NOTICE** the LC_ALL `environment_variable`... older versions of rabbitmq I never had this problem but moving to using the latest this became issue but found this solution in #671. Not fully sure this should have to be fixed by `LC_ALL` but it works.

**Comment by wyardley** [comment] 2018-03-21 05:19
Yeah, should definitely clarify the docs on the erlang thing. I was part of the decision to use OS packages by default, but in hindsight, might be time to re-evaluate that. At any rate, anyone doing a new setup with RabbitMQ would definitely want to use the newer version, and while the param is documented, we should maybe make the docs on setting `repos_ensure` bit more prominent in the README as well. docs PRs happily reviewed / accepted.

Maybe the issue you're seeing has to do with 
```puppet
require  => Service['rabbitmq-server'],
```
messing up the ordering? I spun up the acceptance test on a CentOS instance with BEAKER_destroy=no and manually ran the below manifest [with a sensu user not already existing], and it seems to apply Ok:

```
[root@centos-7-x64 tmp]# rpm -qa | grep rabbitmq
rabbitmq-server-3.3.5-34.el7.noarch
[root@centos-7-x64 tmp]# cat apply_manifest.pp.WnswOY
class { 'rabbitmq':
  service_manage    => true,
  port              => 5672,
  delete_guest_user => true,
  admin_enable      => true,
} ->

rabbitmq_user { 'sensu':
  password => 'readonly',
}
-> rabbitmq_vhost { '/sensu':
  ensure  => present,
}
-> rabbitmq_user_permissions { 'sensu@/sensu':
  configure_permission => '.*',
  read_permission      => '.*',
  write_permission     => '.*',
}
[root@centos-7-x64 tmp]# puppet apply apply_manifest.pp.WnswOY
Warning: /etc/puppetlabs/puppet/hiera.yaml: Use of 'hiera.yaml' version 3 is deprecated. It should be converted to version 5
   (in /etc/puppetlabs/puppet/hiera.yaml)
Notice: Compiled catalog for centos-7-x64.axsops.net in environment production in 0.72 seconds
Notice: /Stage[main]/Main/Rabbitmq_user[sensu]/ensure: created
Notice: /Stage[main]/Main/Rabbitmq_vhost[/sensu]/ensure: created
Notice: /Stage[main]/Main/Rabbitmq_user_permissions[sensu@/sensu]/ensure: created
Notice: Applied catalog in 1.89 seconds
```
It does seem that if the user isn't created first, this will cause an error, because of the `run_with_retries()` in https://github.com/voxpupuli/puppet-rabbitmq/blob/master/lib/puppet/provider/rabbitmq_user_permissions/rabbitmqctl.rb#L18-L19 (it's probably seeing that command exit 2 and re-running until the retry limit).

**Comment by wyardley** [comment] 2018-04-03 21:53
Can someone see if #690 fixes this?
Also, could the folks on affected systems let us know if you have anything in `/etc/default/locale`?

**Comment by wyardley** [comment] 2018-04-05 23:47
So can seem to reproduce that error w/ rabbitmqctl if I install newer Erlang and RabbitMQ and then set the locale to C.
Even if I follow the various shell scripts down to what they call, it seems to be coming from this:
```
erl +B -boot start_clean -noinput -noshell -hidden -smp enable -kernel inet_dist_listen_min 35672 -kernel inet_dist_listen_max 35682 -sasl errlog_type error -mnesia dir "/var/lib/rabbitmq/mnesia/rabbit@ubuntu-server-1604-x64" -run escript start -escript main rabbitmqctl_escript -extra /usr/lib/rabbitmq/lib/rabbitmq_server-3.7.4/escript/rabbitmqctl
```
So I think this is coming directly from RabbitMQ.

I did open https://github.com/rabbitmq/rabbitmq-server/issues/1572 to try and get a bit of clarity... if it really needs UTF-8, we could extend #690 to set default env to UTF-8, but that seems a bit drastic.

I'm working on a more specific fix to ignore this line as well.

**Comment by wyardley** [comment] 2018-04-09 22:24
Merged a fix that forces `en_US.UTF-8` vs. `C`, which fixes in my test environment.

**Closed** 2018-04-09 22:33 UTC
Labels: bug
